import { app, BrowserWindow, ipcMain, dialog, protocol } from 'electron';
import { testFFmpeg, extractVideoMetadata } from './main/ffmpeg';
import { APP_CONFIG } from './shared/constants';
import * as path from 'path';
import * as fs from 'fs';

// Register protocol as standard BEFORE app is ready
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'video-local',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
      bypassCSP: true, // This bypasses CSP!
    },
  },
]);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// ====================================================================
// IPC Handlers - Must be registered before app is ready
// ====================================================================
console.log('🔧 Registering IPC handlers...');

ipcMain.handle('open-file-dialog', async () => {
  console.log('📂 IPC: open-file-dialog called');
  const result = await dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [
      { name: 'Videos', extensions: ['mp4', 'mov', 'avi', 'm4v', 'mkv', 'webm'] }
    ]
  });
  
  if (result.canceled) {
    console.log('📂 IPC: User cancelled file selection');
    return null;
  }
  
  console.log('📂 IPC: File selected:', result.filePaths[0]);
  return result.filePaths[0];
});

ipcMain.handle('extract-metadata', async (_event, filePath: string) => {
  console.log('🎬 IPC: extract-metadata called for:', filePath);
  try {
    const metadata = await extractVideoMetadata(filePath);
    console.log('🎬 IPC: Metadata extracted successfully');
    return metadata;
  } catch (error) {
    console.error('🎬 IPC: Metadata extraction failed:', error);
    throw error;
  }
});

console.log('✅ IPC handlers registered successfully');

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    title: APP_CONFIG.name,
    height: 800,
    width: 1400,
    minWidth: 1200,
    minHeight: 700,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: false, // Allow loading local video files
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development.
  if (process.env.NODE_ENV !== 'production') {
    mainWindow.webContents.openDevTools();
  }

  // Test FFmpeg on startup
  console.log('🔍 Testing FFmpeg integration...');
  testFFmpeg().then((success) => {
    if (success) {
      console.log('✅ FFmpeg integration verified successfully!');
      console.log('✅ Video processing ready for MVP development!');
      
      // Send success message to renderer process
      mainWindow.webContents.send('ffmpeg-status', { success: true });
    } else {
      console.error('❌ FFmpeg integration failed - video operations may not work');
      console.error('❌ Check FFmpeg installation and PATH');
      
      // Send failure message to renderer process
      mainWindow.webContents.send('ffmpeg-status', { success: false });
    }
  }).catch((error) => {
    console.error('❌ FFmpeg test error:', error);
    mainWindow.webContents.send('ffmpeg-status', { success: false, error: error.message });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // Register custom protocol using stream for better video support
  protocol.registerStreamProtocol('video-local', (request, callback) => {
    // Remove the protocol prefix
    let url = request.url.substring('video-local:///'.length);
    
    // Decode URL encoding (handles spaces and special characters)
    const decodedPath = decodeURIComponent(url);
    
    console.log('📹 Protocol handler called');
    console.log('📹 Raw URL:', request.url);
    console.log('📹 Decoded path:', decodedPath);
    
    try {
      // Check if file exists
      if (!fs.existsSync(decodedPath)) {
        console.error('📹 File not found:', decodedPath);
        callback({ statusCode: 404 });
        return;
      }
      
      console.log('📹 File exists, streaming:', decodedPath);
      
      // Get file stats for Content-Length
      const stat = fs.statSync(decodedPath);
      const fileSize = stat.size;
      
      // Determine MIME type based on extension
      const ext = path.extname(decodedPath).toLowerCase();
      const mimeTypes: { [key: string]: string } = {
        '.mp4': 'video/mp4',
        '.mov': 'video/quicktime',
        '.avi': 'video/x-msvideo',
        '.mkv': 'video/x-matroska',
        '.webm': 'video/webm',
        '.m4v': 'video/x-m4v',
      };
      const mimeType = mimeTypes[ext] || 'video/mp4';
      
      // Parse Range header if present (needed for video seeking)
      const rangeHeader = request.headers['Range'] || request.headers['range'];
      let start = 0;
      let end = fileSize - 1;
      let statusCode = 200;
      
      if (rangeHeader) {
        const parts = rangeHeader.replace(/bytes=/, '').split('-');
        start = parseInt(parts[0], 10);
        end = parts[1] ? parseInt(parts[1], 10) : end;
        statusCode = 206; // Partial Content
        
        console.log(`📹 Range request: bytes ${start}-${end}/${fileSize}`);
      }
      
      console.log('📹 MIME type:', mimeType);
      console.log('📹 File size:', fileSize);
      console.log('📹 Status code:', statusCode);
      
      // Create read stream with range
      const stream = fs.createReadStream(decodedPath, { start, end });
      
      const headers: Record<string, string> = {
        'Content-Type': mimeType,
        'Accept-Ranges': 'bytes',
        'Content-Length': (end - start + 1).toString(),
      };
      
      if (statusCode === 206) {
        headers['Content-Range'] = `bytes ${start}-${end}/${fileSize}`;
      }
      
      callback({
        statusCode,
        headers,
        data: stream,
      });
    } catch (error) {
      console.error('📹 Protocol handler error:', error);
      callback({ statusCode: 500 });
    }
  });
  
  console.log('✅ Custom video protocol registered (stream mode with range support)');
  
  // Create the main window
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
