import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import { testFFmpeg, extractVideoMetadata } from './main/ffmpeg';
import { APP_CONFIG } from './shared/constants';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// ====================================================================
// IPC Handlers - Must be registered before app is ready
// ====================================================================
console.log('🔧 Registering IPC handlers...');

ipcMain.handle('open-file-dialog', async () => {
  console.log('📂 IPC: open-file-dialog called');
  const result = await dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [
      { name: 'Videos', extensions: ['mp4', 'mov', 'avi', 'm4v', 'mkv', 'webm'] }
    ]
  });
  
  if (result.canceled) {
    console.log('📂 IPC: User cancelled file selection');
    return null;
  }
  
  console.log('📂 IPC: File selected:', result.filePaths[0]);
  return result.filePaths[0];
});

ipcMain.handle('extract-metadata', async (_event, filePath: string) => {
  console.log('🎬 IPC: extract-metadata called for:', filePath);
  try {
    const metadata = await extractVideoMetadata(filePath);
    console.log('🎬 IPC: Metadata extracted successfully');
    return metadata;
  } catch (error) {
    console.error('🎬 IPC: Metadata extraction failed:', error);
    throw error;
  }
});

console.log('✅ IPC handlers registered successfully');

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    title: APP_CONFIG.name,
    height: 800,
    width: 1400,
    minWidth: 1200,
    minHeight: 700,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development.
  if (process.env.NODE_ENV !== 'production') {
    mainWindow.webContents.openDevTools();
  }

  // Test FFmpeg on startup
  console.log('🔍 Testing FFmpeg integration...');
  testFFmpeg().then((success) => {
    if (success) {
      console.log('✅ FFmpeg integration verified successfully!');
      console.log('✅ Video processing ready for MVP development!');
      
      // Send success message to renderer process
      mainWindow.webContents.send('ffmpeg-status', { success: true });
    } else {
      console.error('❌ FFmpeg integration failed - video operations may not work');
      console.error('❌ Check FFmpeg installation and PATH');
      
      // Send failure message to renderer process
      mainWindow.webContents.send('ffmpeg-status', { success: false });
    }
  }).catch((error) => {
    console.error('❌ FFmpeg test error:', error);
    mainWindow.webContents.send('ffmpeg-status', { success: false, error: error.message });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
